# Generated by Django 2.2.5 on 2019-09-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0002_auto_20190917_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
